export const home = {
  earthTitle: "Earth",
  earthDescription: `Earth is the third planet from the Sun and the only planet known to have life. It has an oxygen-rich atmosphere and abundant water resources. `,
  jupiterTitle: "Jupiter",
  jupiterDescription: `Jupiter is the largest planet in the Solar System and the fifth from the Sun. It has a thick atmosphere and a distinct feature known as the Great Red Spot.`,
  marsTitle: "Mars",
  marsDescription: `Mars is the fourth planet from the Sun and is known as the Red Planet due to its reddish soil. It has ice caps at its poles and evidence of liquid water in the past.`,
  mercuryTitle: "Mercury",
  mercuryDescription: `Mercury is the closest planet to the Sun and the smallest planet in the Solar System. Its surface is covered in impact craters, and it has a thin atmosphere.    `,
  neptuneTitle: "Neptune",
  neptuneDescription: `Neptune is the eighth planet from the Sun and is known for its extremely strong winds. It has an atmosphere of methane, giving it a beautiful blue color.    `,
  saturnTitle: "Saturn",
  saturnDescription: `Saturn is the sixth planet from the Sun and the second-largest in the Solar System. It is famous for its beautiful and extensive ring system. `,
  uranusTitle: "Uranus",
  uranusDescription: `Uranus is the seventh planet from the Sun and is unique for its sideways rotation. It has an atmosphere rich in hydrogen and helium.    `,
  venusTitle: "Venus",
  venusDescription: `Venus is the second planet from the Sun and has a thick atmosphere that causes a severe greenhouse effect. Its surface is extremely hot.    `,
};
